const Engine = Matter.Engine;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
const World = Matter.World;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
const Bodies = Matter.Bodies;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
const Body = Matter.Body;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
const Render = Matter.Render;                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
function preload(){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
function setup(){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	createCanvas(1400,700);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	engine = Engine.create();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	world = engine.world;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 ground = new Ground(width/2,675,1600,20)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 bin1 = new Dustbin(1100,591,20,150)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 bin2 = new Dustbin(1300,591,20,150)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 bin3 = new Dustbin(1200,657,180,20)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 ball = new Ball(200,600,25)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 var render = Render.create({
	element: document.body,
	engine: engine,
	options: {
	  width: 1600,
	  height: 700,
	  wireframes: false
	}
  });

  Engine.run(engine);
  Render.run(render);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
function draw(){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
  rectMode(CENTER);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
background(0)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 ground.display()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 bin1.display()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 bin2.display()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 bin3.display()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 ball.display()   
 
 text("press space to play again",700,100)
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
function keyPressed(){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	if(keyCode === UP_ARROW ){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
		Matter.Body.applyForce(ball.body,ball.body .position,{x:35,y:-35})                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	}        
	if(keyCode === 32){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
		Matter.Body.setPosition(ball.body,{x:200,y:600})                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	} 

} 
                                                                                                                                                                                                                                                                                                                                                              